### PR TITLE
Add container prop on the component and send it to b-popover component

### PR DESCRIPTION
**Pull request by KenoKokoro**
I needed ti ability for the popover to appear inside a specific div, since I had a `@mouseover` event there followed by `@mouseleave`. So when the popup appeared the `@mouseleave` was triggered and causing unwanted behavior. This is because the popover is glued to the body.
So to fix this: Inside the `ClickConfirm.vue`

```js
props: {
   ...
   container: {
      type: String,
      default: null,
      validator(value) {
         return typeof value === 'string' || value === null;
      }
   }
   ...
}
```

And inside the template just this:
```html
...
<b-popover
            :container="container"
            ...>
...
```

Everything else remains the same.
Like this I can send to `<click-confirm container="id-of-my-div">...</click-confirm>` and the mess is fixed because the confirmation element will be inside my div.

Cheers.

### CODE REVIEW

**Comment by KenoKokoro** [comment]
Also, forgot to mention that this won't affect any of the default configuration. The container prop is not required. From the `b-popover` documentation it says that if `null` is provided as value, it will append it to the body (just like it is before this PR`

**Comment by GregPeden** [comment]
Yeah this seems fine because it affects nothing else.

Your validator is interesting in that it doesn't seem to do anything beyond the default "type" check. Any other reason for including it? The Bootstrap-vue component itself does not include a similar validator.

Reference: https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/mixins/toolpop.js#L53

**Comment by KenoKokoro** [comment]
I did it just to make sure that `null` value is sent to the `b-popover`, I am not really in depth familiar with the vuejs props, so I wasn't sure what value would be sent to the `b-popover` if the container is not set on the `click-confirm`. So to avoid having it `undefined`, I just put the validator.
It might have been fine just with `default: null` ?

**Comment by KenoKokoro** [comment]
So, is it ready for merge? I am really waiting for this PR.

**Comment by GregPeden** [comment]
Take out the validation test please and add it to the documentation. They're normally great except yours is not doing anything the default validation doesn't do.

I was not able to get around to updating the documentation for this last week but if you want to do that, go ahead. Just copy the description from Bootstrap-vue for it.

**Comment by KenoKokoro** [comment]
Alright, then.
I updated the property section on the documentation and removed the validation on the property.

**Comment by GregPeden** [comment]
I don't know why but I cannot publish to NPM at the moment. I'm on the road so I cannot spend too long troubleshooting this now however you could grab the build tagged with v2.2.0 by build ID for now.

**Pull request merged**
